name: Test and Build TETI Ask

on:
    push:
        branches:
            - main
        paths:
            - "frontend/**"

jobs:
    test-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Test and Build
              uses: actions/setup-node@v2
              with:
                  node-version: "18"
            - run: npm i
            - run: npm run build
