name: Test and Build TETI Ask

on:
    push:
        branches: [main]

jobs:
    test-build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - uses: actions/checkout@v2
            - name: Test and Build
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - run: npm i
            - run: npm run build
